### ISSUE TITLE
WIFI and SSH help

### ISSUE THREAD

**Issue by atliia** [xblax/flashforge_ad5m_klipper_mod#114]
I am trying to ssh from windows command line to implement https://github.com/xblax/flashforge_adm5_klipper_mod/discussions/69

When I ssh @root I am prompted for password. I found Username root  password klipper in the docs. But, I am not able to figure out how to connect with that. I did manage to connect to wifi one time. From the printer. However, I was not able to connect to the printer in orca or mainsail from wifi. I did connect to the printer over ethernet in orca. But, could not connect with mainsail. When I am connected via wifi only, and ping I get a timeout.

**Comment by THEGxHOxST** [comment]
I'd run a Lan scan from a phone on the same network and confirm its Wi-Fi IP, Just search in your app market to find one.
For Windows, Solarputty is a great piece of software that handles all of that for you.
Linux its just "ssh root@youripadress", accept the key and input the password klipper
Once you get in, I recommend making the IP static within IWD because my router likes to give it a different IP every time...

cd /var/lib/iwd 
ls
nano "yourwifi".psk 
add to the bottom of that file.
[IPv4]
Address=The IP you'd like your printer to have
Netmask=255.255.255.0
Gateway=your router's IP
Broadcast=Same as the IP you'd like your printer to have
DNS=1.1.1.1
