### ISSUE TITLE
Wifi/Internet showing 0.0.0.0 as IP address.

### ISSUE THREAD

**Issue by 0parenthesis** [xblax/flashforge_ad5m_klipper_mod#225]
Basically no matter how I have it connected (wifi 2.4/5ghz) or ethernet I can't get an IP for the printer. always just shows 0.0.0.0 on klipper screen. Tried guppy as well. Seeing if anyone else had this issue.

**Comment by consp** [comment]
Sometimes it does that unfortunately, usually it's a dual configuration e.g. both ethernet and wifi but not always. I'm pretty sure it's related to the way it asks for the IP and gets the listening IP (which can be 0.0.0.0) instead of the actual IP. I'd call it a bug but I'm not sure it's fixable. Don't really have a good solution for it unfortunately.

Here are two ways to find it out outside of the printer:
* Easy: You can also look in your router/wifi access point configuration to see the ip, it's usually somewhere near dhcp/dhcp leases/assigned addresses.
* Medium: If you are on linux: install arp-scan, run `sudo arp-scan -I wlan0 192.168.0.0/16` and wait till you see something which resembles the printer (or try them all). Replace `wlan0` with the wifi interface and `192.168.0.0/16` with your wifi IP range and netmask.
