### ISSUE TITLE
Chamber and exhaust fan macros

### ISSUE THREAD

**Issue by KaruroChori** [xblax/flashforge_ad5m_klipper_mod#54]
### Discussed in https://github.com/xblax/flashforge_adm5_klipper_mod/discussions/53

The original firmware in the pro version supports the VOC readout to keep the fan running so that all air is filtered before opening the printer.
At least, this is what I read, I do not own that model.

Still I think it would be nice to support this.

**Comment by KaruroChori** [comment]
@johncotten I'll just copy a post from the other related issue:

>I think that in order to properly calibrate it, and to fully implement some of the original functionalities, we need the base "temperature" as base level, and maybe the level you get while printing abs while enclosed. This should provide some realistic typical values to use as reference.
>
>In terms of visualization, the fact it is shown as a temperature value is not a real problem, except that it could be confusing for the end user. I have no idea if there is a way to change visualization and units on mainsail/fluidd.

**Comment by KaruroChori** [comment]
Not sure about that.

The issue is not just about quantity but also quality so to speak. That kind of sensor is not very specific and will probably detect a wide range of different chemicals. In the case of ABS for example, the main issue we have are styrenes; other materials will release clorine compounds, And others formaldehyde. The tolerance to each is based on the concentration in the environment, and for some there is no safe exposure level.

Even PLA an PETG will release VOCs, but it is not a matter of quantity, just the fact their chemistry is different and less toxic. Using PLA or PETG as ground reference will not provide a meaningful measure to tolerable levels of others types.

**Comment by KaruroChori** [comment]
Sadly I am in the opposite situation, I often use ABS and ASA, but I only have the base model.
Let me know if you need any assistance, or we can just wait for someone else to test it :D.

**Comment by KaruroChori** [comment]
By the way, if you want to test it for PLA and PETG as well please do that. It is not a useful as for ABS and other materials, but since that feature is there some might want to use it regardless. Having a reference value for each materials would be best.

**Comment by KaruroChori** [comment]
This is quite strange. You were able to raise it with the glue right?

**Comment by consp** [comment]
> TVOC level hasn't moved above 23 degrees

Printed with PLA, got up to 37 without any fans (was a testcube). Did another cube. Turned external+internal in external mode on, slowly dropped and after print went down to about 33. After enabeling the chamber fan (and waiting till the bed was cold) it was 27.

**Comment by Tiwatz** [comment]
> I'm starting to wonder if my sensor is bad. Glue only takes it up to 32 degrees. PLA did change, stayed at 23...

When I'm printing PLA with door + lid closed but external + internal fans on, my sensor is pretty stable at 27. 23-24 while idle. Going to try some ASA soon.

**Comment by consp** [comment]
> I'm starting to wonder if my sensor is bad. Glue only takes it up to 32 degrees. PLA did change, stayed at 23...

Just applied glue and it went to 500

**Comment by consp** [comment]
> Is that the TVOC Level or Load Cell? My Purple is Load Cell, and it does change a lot, but it also goes up when I press on the bed too...

Load cell is orange. That was me pressing the glue stick on it.

**Comment by consp** [comment]
Wireless power > 10W is a PITA with respect to efficiency but under that can be done with cots stuff!

Observations with the sensor so far:

* Drops to "ambient" (which is about 24 here) printing PLA with doors open (since my PLA definitely needs coolness).
* Glue stick on cold bed wil slowly evaporate and slowly rise to about 100-150 closed door before starting to drop off again.
* Glue stick on hot-ish bed will spike to 500 in seconds which is probably saturation.
* Using "hairsprayadhesive" has the same effect as glue on hot bed :stuck_out_tongue: 
* After reaching 500 slowly drops with internal circulation after a while, faster with both (as expected but since we don't know everything, it's just an observation)
* Printing with ABS from a clean env (no glue) will slowly rise to about 50 with internal circulation on and then level off before dropping when cooling down with both fans set to external (hotbed off, box closed)

I'm going to investigate making an new duct to put a bigger fan in (in due time), when using PLA I want some cold air into the device as it otherwise rises to about 30-40c which has annoying minor sideffects which are not present with the door open (I'm no expert on plastics and 3d printing so might just be settings). Currently making ABS prints so cooling doesn't matter too much.

**Comment by consp** [comment]
> The internal fan door is installed incorrectly

It's unknown if it happens often but in at least two cases the fan was offset by 90 degrees, this causes the servo to make nasty noises when either in external or internal mode. If you hear a "frustrated servo" noise from the machine (which is not one of the fans) it's likely you have the same issue.

**Comment by consp** [comment]
Should we close this issue? The main issue is included in the v0.4 already.
